import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'

import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'user',
        path: '',
        title: 'User',
        translateKey: 'nav.services',
        icon: 'user',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'user.dashboard',
                path: '/app/user-dashboard',
                title: 'User Dashboard',
                translateKey: 'nav.applications',
                icon: 'home',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'user.profile',
                path: '/app/user/profile',
                title: 'My Profile(user)',
                translateKey: 'nav.applications',
                icon: 'user',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'user.applications',
                path: '/app/user/applications',
                title: 'My Applications(user)',
                translateKey: 'nav.applications',
                icon: 'applications',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'services',
        path: '',
        title: 'Services',
        translateKey: 'nav.services',
        icon: 'services',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'services.birth',
                path: '/app/forms/birth',
                title: 'Birth',
                translateKey: 'nav.collapseMenu.item1',
                icon: 'birth',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'services.marriage',
                path: '/app/forms/marriage',
                title: 'Marriage',
                translateKey: 'nav.collapseMenu.item2',
                icon: 'marriage',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'services.death',
                path: '/app/forms/death',
                title: 'Death',
                translateKey: 'nav.collapseMenu.item2',
                icon: 'death',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'clerk',
        path: '',
        title: 'Clerk',
        translateKey: 'nav.services',
        icon: 'clerk',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'clerk.dashboard',
                path: '/app/clerk-dashboard',
                title: 'Clerk Dashboard',
                translateKey: 'nav.applications',
                icon: 'home',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'clerk.profile',
                path: '/app/clerk/profile',
                title: 'My Profile(clerk)',
                translateKey: 'nav.applications',
                icon: 'clerk',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'clerk.applications',
                path: '/app/clerk/applications',
                title: 'My Applications(clerk)',
                translateKey: 'nav.applications',
                icon: 'applications',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },

    {
        key: 'admin.dashboard',
        path: '/app/admin-dashboard',
        title: 'Admin Dashboard',
        translateKey: 'nav.applications',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'admin.profile',
        path: '/app/admin/profile',
        title: 'My Profile(admin)',
        translateKey: 'nav.applications',
        icon: 'admin',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'Manage',
        path: '',
        title: 'Manage',
        translateKey: 'nav.services',
        icon: 'manage',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'admin.clerks',
                path: '/app/admin/clerks-page ',
                title: 'Clerks',
                translateKey: 'nav.collapseMenu.item2',
                icon: 'clerks',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'admin.users',
                path: '/app/admin/users-page ',
                title: 'Users',
                translateKey: 'nav.collapseMenu.item2',
                icon: 'users',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'admin.states',
                path: '/app/admin/states-page',
                title: 'State',
                translateKey: 'nav.collapseMenu.item2',
                icon: 'states',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'admin.district',
                path: '/app/admin/districts-page',
                title: 'Districts',
                translateKey: 'nav.collapseMenu.item2',
                icon: 'districts',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'admin.offices',
                path: '/app/admin/offices-page ',
                title: 'Offices',
                translateKey: 'nav.collapseMenu.item2',
                icon: 'offices',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'admin.holidays',
                path: '/app/admin/holidays-page ',
                title: 'Holidays',
                translateKey: 'nav.collapseMenu.item2',
                icon: 'holidays',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },

    {
        key: 'login',
        path: '/sign-in',
        title: 'Login',
        translateKey: 'nav.applications',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },

    // {
    //     key: 'groupMenu',
    //     path: '',
    //     title: 'Group Menu',
    //     translateKey: 'nav.groupMenu.groupMenu',
    //     icon: 'groupMenu',
    //     type: NAV_ITEM_TYPE_TITLE,
    //     authority: [],
    //     subMenu: [
    //         {
    //             key: 'groupMenu.single',
    //             path: '/group-single-menu-item-view',
    //             title: 'Group single menu item',
    //             translateKey: 'nav.groupMenu.single',
    //             icon: 'groupSingleMenu',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //         {
    //             key: 'groupMenu.collapse',
    //             path: '',
    //             title: 'Group collapse menu',
    //             translateKey: 'nav.groupMenu.collapse.collapse',
    //             icon: 'groupCollapseMenu',
    //             type: NAV_ITEM_TYPE_COLLAPSE,
    //             authority: [],
    //             subMenu: [
    //                 {
    //                     key: 'groupMenu.collapse.item1',
    //                     path: '/group-collapse-menu-item-view-1',
    //                     title: 'Menu item 1',
    //                     translateKey: 'nav.groupMenu.collapse.item1',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [],
    //                     subMenu: [],
    //                 },
    //                 {
    //                     key: 'groupMenu.collapse.item2',
    //                     path: '/group-collapse-menu-item-view-2',
    //                     title: 'Menu item 2',
    //                     translateKey: 'nav.groupMenu.collapse.item2',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [],
    //                     subMenu: [],
    //                 },
    //             ],
    //         },
    //     ],
    // },
]

export default navigationConfig
